# Inspired by https://github.com/semantic-release/github/blob/master/.github/workflows/release.yml
name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  quality:
    name: quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: | 
          9.0.x
    - name: Restore
      run: dotnet restore
    - name: Unit Tests
      run: dotnet test
    - name: Build Release
      run: dotnet build -tl -c Release
  release:
    needs: quality
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npm install --no-save semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/github @semantic-release/npm @semantic-release/git semantic-release-replace-plugin semantic-release-presets
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
          TEAMS_WEBHOOK_DISABLED: true
